__author__ = 'Yifei'

HEADER_OFFSET = 0
INDEX_OFFSET = 4
LENGTH_OFFSET = 5
CHECKSUM_OFFSET = 6
PACKET_CONSTANT_OFFSET = 7
OPERAND_OFFSET = 7
PAYLOAD_OFFSET = 8
MAX_PAYLOAD_LENGTH = 255
MIN_PACKET_LENGTH = 4 + 1 + 1 + 1
PROTOSBN1_HEADER_BYTES = [0x53, 0x42, 0x4e, 0x31]
